site_name: Pritam Dash
site_url: https://ipritamdash.github.io/portfolio/
repo_url: https://github.com/ipritamdash/portfolio
repo_name: ipritamdash

theme:
  name: material
  # custom_dir: overrides (Keep this commented out)
  palette:
    # Dark Mode (Slate + Cyan) - The "Developer" Look
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode
    # Light Mode (White + Indigo) - The "Paper" Look
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  font:
    text: Plus Jakarta Sans
    code: JetBrains Mono

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Projects:
      - RAG Research Backend: projects/rag.md
      - Indian Art Music Separation: projects/music.md
      - Maya Voice Assistant: projects/maya.md
  - Resume & Contact: contact.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
